flask_app/playlists/routes.py
import random
from flask import Blueprint, render_template, url_for, redirect, request, flash
from flask_login import current_user, login_required, login_user, logout_user
import uuid
from ..models import Playlist, User
from ..forms import SearchForm, PlaylistMetadataForm, PlaylistSongForm
from ..client import SongClient
playlists = Blueprint('playlists', __name__)

@playlists.route('/', methods=['GET', 'POST'])
def index():
    form = SearchForm()
    if form.validate_on_submit():
        return redirect(url_for('playlists.search', query=form.search_query.data))
    
    #get top 10 playlists
    playlists = Playlist.objects.order_by('-likes').limit(10)


    


    return render_template('index.html', title="Home", form=form, playlists=playlists)

#create playlist
@login_required
@playlists.route('/create', methods=['GET', 'POST'])
def create():
    #check if user is logged in
    if not current_user.is_authenticated:
        flash('You must be logged in to create a playlist', 'danger')
        return redirect(url_for('user.login'))
    else:
        form = PlaylistMetadataForm()
        if form.validate_on_submit():
            playlist = Playlist(name=form.name.data, description=form.description.data, owner=current_user._get_current_object(), uuid=str(uuid.uuid4()), songs=[])
            print(playlist.owner)
            playlist.save()
            return redirect(url_for('playlists.edit', uuid=playlist.uuid))

    return render_template('create.html', title="Create Playlist", form=form)

@playlists.route('/edit/<uuid>', methods=['GET', 'POST'])
def edit(uuid):
    playlist = Playlist.objects(uuid=uuid).first()
    if playlist is None or  playlist.owner != current_user._get_current_object():
        flash('You do not have permission to edit this playlist', 'danger')
        return redirect(url_for('playlists.index'))
    else:
        playForm = PlaylistSongForm()
        if playForm.validate_on_submit():
            song = SongClient().get_track(playForm.artist.data, playForm.song.data)
            
            try:
                song.mbid
            
                return redirect(url_for('playlists.addSong', uuid=playlist.uuid, mbid=song.mbid))
            except:
                flash('Song not found', 'danger')
                return redirect(url_for('playlists.edit', uuid=playlist.uuid))

        form = PlaylistMetadataForm()
        if form.validate_on_submit():
            playlist.name = form.name.data
            playlist.description = form.description.data
            playlist.save()
            return redirect(url_for('playlists.edit', uuid=playlist.uuid))
        else:
            form.name.data = playlist.name
            form.description.data = playlist.description

   
      
        
        songs = []

        for mbid in playlist.songs:
            songs.append(SongClient().get_track_by_mbid(mbid))

        numSongs = 16 // ( len(songs) + 1)
        
        top = []
        for song in songs:
            top.extend(SongClient().get_topN_tracks(numSongs, song.artist))
        
        random.shuffle(top)

        


            



        return render_template('edit.html', title="Edit Playlist", form=form, playForm = playForm, songs=songs, playlist=playlist, top15=top)

@playlists.route('/delete/<uuid>', methods=['GET', 'POST'])
def delete(uuid):
    playlist = Playlist.objects(uuid=uuid).first()
    if playlist is not None:
        if playlist.owner == current_user._get_current_object():
            playlist.delete()
            flash('Playlist deleted', 'success')
            return redirect(url_for('user.account'))
        else:
            flash('You do not have permission to delete this playlist', 'danger')
            return redirect(url_for('playlists.index'))
        
    else:
        flash('Playlist not found', 'danger')
        return redirect(url_for('user.account'))
    
@playlists.route('/search/<query>', methods=['GET', 'POST'])
def search(query):
    form = SearchForm()
    if form.validate_on_submit():
        return redirect(url_for('playlists.search', query=form.search_query.data))

    
    #get all playlists that match query
    playlists = Playlist.objects(name__icontains=query).order_by('-likes')




    return render_template('search.html', title="Search", playlists=playlists, query=query, form=form)

@playlists.route('/deleteSong/<mbid>/<uuid>', methods=['GET', 'POST'])
def deleteSong(uuid, mbid):
    playlist = Playlist.objects(uuid=uuid).first()
    if playlist is None or  playlist.owner != current_user._get_current_object():
        flash('You do not have permission to edit this playlist', 'danger')
        return redirect(url_for('playlists.index'))
    else:
        playlist.songs.remove(mbid)
        playlist.duration -= SongClient().get_track_by_mbid(mbid).duration
        playlist.save()
        return redirect(url_for('playlists.edit', uuid=playlist.uuid))
    

@playlists.route('/addSong/<mbid>/<uuid>', methods=['GET', 'POST'])
def addSong(uuid, mbid):
    playlist = Playlist.objects(uuid=uuid).first()
    if playlist is None or  playlist.owner != current_user._get_current_object():
        flash('You do not have permission to edit this playlist', 'danger')
        return redirect(url_for('playlists.index'))
    else:
        playlist.songs.append(mbid)
        playlist.duration += SongClient().get_track_by_mbid(mbid).duration
        playlist.save()
        return redirect(url_for('playlists.edit', uuid=playlist.uuid))
    
@playlists.route('/view/<uuid>', methods=['GET', 'POST'])
def view(uuid):
    playlist = Playlist.objects(uuid=uuid).first()
    if playlist is None:
        flash('Playlist not found', 'danger')
        return redirect(url_for('playlists.index'))
    else:
        song = SongClient().get_track_by_mbid(playlist.songs[0])
        songs = []

        for mbid in playlist.songs:
        
            songs.append(SongClient().get_track_by_mbid(mbid))

        
        form = SearchForm()
        if form.validate_on_submit():
            return redirect(url_for('playlists.search', query=form.search_query.data))
        
        total_duration = playlist.duration
 

        liked = False
        if current_user.is_authenticated:
            if playlist.uuid in current_user.liked_playlists:
                liked = True
            



        

        return render_template('view.html', title="View Playlist", playlist=playlist, songs=songs, form=form, total_duration=total_duration, liked=liked)
    

@playlists.route('/like/<uuid>', methods=['GET', 'POST'])
def like(uuid):
    if not current_user.is_authenticated:
        flash('You must be logged in to like a playlist', 'danger')
        return redirect(url_for('user.login'))
    else:
        playlist = Playlist.objects(uuid=uuid).first()
        if playlist is None:
            flash('Playlist not found', 'danger')
            return redirect(url_for('playlists.index'))
        else:
            if playlist.uuid in current_user.liked_playlists:
                current_user.liked_playlists.remove(playlist.uuid)
                current_user.save()
                playlist.likes = playlist.likes - 1
                playlist.save()
                return redirect(url_for('playlists.view', uuid=playlist.uuid))
            else:
                current_user.liked_playlists.append(playlist.uuid)
                current_user.save()
                playlist.likes += 1
                playlist.save()
                return redirect(url_for('playlists.view', uuid=playlist.uuid))
            
@playlists.route('/about', methods=['GET', 'POST'])
def about():
    return render_template('about.html', title="About")

flask_app/user/routes.py
from flask import Blueprint, redirect, url_for, render_template, flash, request
from flask_login import current_user, login_required, login_user, logout_user

from .. import bcrypt
from ..models import User, Playlist
from ..forms import LoginForm, RegistrationForm, SearchForm
from ..client import SongClient

user = Blueprint("user", __name__)

@user.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("playlists.index"))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.objects(username=form.username.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user)
            flash("You have been logged in!", "success")
            return redirect(url_for("playlists.index"))
        else:
            flash("Login Unsuccessful. Please check username and password", "danger")


    return render_template("login.html", form=form)

    

@user.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("playlists.index"))

@user.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("playlists.index"))

    form = RegistrationForm()
    if form.validate_on_submit():
        hashed = bcrypt.generate_password_hash(form.password.data).decode("utf-8")
        user = User(username=form.username.data, email=form.email.data, password=hashed)
        user.save()

        return redirect(url_for("user.login"))
    
    print(form.errors)

    return render_template("register.html", title="Register", form=form)

@login_required
@user.route('/account', methods=['GET', 'POST'])
def account():
    if not current_user.is_authenticated:
        flash('You must be logged in to view your account', 'danger')
        return redirect(url_for('user.login'))
    else:
    
        playlists = Playlist.objects(owner=current_user._get_current_object())
    
        
        form = SearchForm()
        if form.validate_on_submit():
            return redirect(url_for('playlists.search', query=form.search_query.data))
        
        #calculate total duration of all playlists
        total_duration = 0
        total_likes  = 0
        for playlist in playlists:
            total_duration += playlist.duration
            total_likes += playlist.likes

        
        return render_template('account.html', title="Account", form=form ,playlists=playlists, total_duration=total_duration, total_likes=total_likes, user = current_user._get_current_object())

#view other users' accounts
@user.route('/view_account/<username>', methods=['GET', 'POST'])
def view_account(username):
    #get playlists of user
    user = User.objects(username=username).first()
    print(user)
    playlists = Playlist.objects(owner=user)
  

    #calculate total duration of all playlists
    total_duration = 0
    total_likes  = 0
    for playlist in playlists:
        total_duration += playlist.duration
        total_likes += playlist.likes

    form = SearchForm()
    if form.validate_on_submit():
        return redirect(url_for('playlists.search', query=form.search_query.data))
    
    return render_template('view_account.html', title="Account", playlists=playlists, total_duration=total_duration, total_likes=total_likes, user = user, form = form)


@user.route('/liked/<username>', methods=['GET', 'POST'])
def liked(username):
    user = User.objects(username=username).first()
    liked = user.liked_playlists
    
    #get liked playlists
    liked_playlists = []
    for playlist in liked:
        pl = Playlist.objects(uuid=playlist).first()
        liked_playlists.append(Playlist.objects(uuid=playlist).first())




  


    return render_template('liked.html', title="Liked", playlists=liked_playlists, user=current_user._get_current_object())

flask_app/templates/about.html
{% extends "header.html" %}
{% block content %}



<div class="mdl-grid">
    
    <div class="mdl-cell--3-col" style="padding-left: 40px; padding-right: 30px;">
        
        <h4>PlaylistsApp</h4>
        <h6>Created by June Philip</h6>
      

       

    </div>
    <div class="mdl-cell--4-col">

        <h6>A simple application that allows users </h6>
        <h6>to make playlists with any songs, </h6>
        <h6>share them publically, receive likes,</h7>
        <h6>and search for playlists, and like them.</h7>
    </div>

    
    <div class="mdl-cell--4-col">
        <h6>Created with 💖 using Flask</h6>
        <h6>and the Spotify API</h6>
        <h6>Hosted on Railway.app</h6>

    </div>


</div>

{% endblock %}

flask_app/templates/account.html
{% extends "header.html" %}
{% block content %}

<script>

</script>




<div class="mdl-grid">
    
    <div class="mdl-cell--3-col" style="padding-left: 40px;">
        
        <h4>Hey, {{ user.username }}!</h4>
        <h6>Account Stats:</h6>
        <h6>Playlists Created: {{ playlists|length }}</h6>
        <h6>Playlists Liked: {{ user.liked_playlists|length }}</h6>
        <h6>Total Duration of All Playlists:  <td class="mdl-data-table__cell--non-numeric">{{ 
            (total_duration / 1000 // 60)|int }}:{{
            (total_duration / 1000 % 60)|int }}
        
        </td></h6>
        <h6>Total Number of Likes: {{ total_likes }}</h6>

        <a href="{{ url_for('user.liked', username=user.username) }}" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent">
            Liked Playlists
        
        </a>


        
       

    </div>
    <div class="mdl-cell--5-col">
        <h4>Search For Playlists!</h4>
        <form action="/" class="" method="POST">
            {{ form.csrf_token }}
            <div class = "mdl-textfield mdl-js-textfield">
                {{ form.search_query(class="mdl-textfield__input", type="text", id="search_query", placeholder="Search For Playlists!", style="width:400;") }}
    
            </div>
            {% if form.search_query.errors %}
            <div class="alert alert-warning" role="alert">
                {% for error in form.search_query.errors %}
                <span style="color: red; font-size: 10;">{{ error }}</span>
                {% endfor %} 
            </div>  
            {% endif %}
            {{ form.submit(class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent") }}
            
    
    
           
        </form>
       

    </div>

    
    <div class="mdl-cell--3-col">
        
        <h4>Your Playlists!</h4>
        {% if playlists %}
        <table class="mdl-data-table mdl-js-data-table">
            <thead>
              <tr>
                <th class="mdl-data-table__cell--non-numeric">Name</th>
                <th class="mdl-data-table__cell--non-numeric">Duration</th>
                <th class="mdl-data-table__cell--non-numeric">Likes</th>
              </tr>
            </thead>
            <tbody>
                {% for pl in playlists %}
                <tr>
                   
                    <td class="mdl-data-table__cell--non-numeric" >{{ pl.name }}</td>
                    <td class="mdl-data-table__cell--non-numeric">{{ 
                        (pl.duration / 1000 // 60)|int }}:{{
                        (pl.duration / 1000 % 60)|int }}
                    
                    </td>
                    <td class="mdl-data-table__cell--non-numeric" >{{ pl.likes }}</td>
                    <td class="mdl-data-table__cell--non-numeric" >
                        <a href="{{ url_for('playlists.edit', uuid=pl.uuid) }}", title="Edit">
                            <span class="material-icons" style="color:black;">
                                edit
                                </span>
                        </a>
                    </td>
                    <td class="mdl-data-table__cell--non-numeric" >
                        <a href="{{ url_for('playlists.delete', uuid=pl.uuid) }}", title="Delete">
                            <span class="material-icons" style="color:black;">
                                delete
                                </span>
                        </a>
                    </td>

                    
                   
                    
                  </tr>
                {% endfor %}
            </tbody>
          </table>
            {% else %}
            <h6>No playlists found!</h6>
            {% endif %}

    </div>


</div>

{% endblock %}

flask_app/templates/base.html
<html lang="en">
<head>



    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.deep_purple-teal.min.css" />
    <script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">



    {% if title %}
    <title>{{ title }}</title>
    {% else %}
    <title>Playlists</title>
    {% endif %}
</head>

<body>
    {% block header %}
    {% endblock %}

</body>

</html>

flask_app/templates/edit.html
{% extends "header.html" %}
{% block content %}

<script>

</script>



<div class="mdl-grid">


    <div class="mdl-cell">
        <form action="" method="post">
            <h4>Add Song</h4>
            {{ form.csrf_token }}

            <div class="mdl-textfield mdl-js-textfield">

                {{ playForm.song(class="mdl-textfield__input", type="text", id="song", autocomplete="off") }}
                {{ playForm.song.label(class="mdl-textfield__label", for="username") }}

            </div>

            <div class="mdl-textfield mdl-js-textfield">

                {{ playForm.artist(class="mdl-textfield__input", type="artist", id="artist", autocomplete="off") }}
                {{ playForm.artist.label(class="mdl-textfield__label", for="artist") }}

            </div>

            {{ playForm.submit(class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect
            mdl-button--accent")
            }}

        </form>

        <form action="" method="post">
            <h4>Edit Info</h4>
            {{ form.csrf_token }}

                <div class="mdl-textfield mdl-js-textfield">
                    {{ form.name(class="mdl-textfield__input", type="text", id="name", autocomplete="off") }}
                    {{ form.name.label(class="mdl-textfield__label", for="name") }}
                    {% if form.name.errors %}
                    <div class="alert alert-warning" role="alert">
                        {% for error in form.name.errors %}
                        <span style="color: red; font-size: 10;">{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% endif %}

                </div>
            <div class="mdl-textfield mdl-js-textfield">

                {{ form.description(class="mdl-textfield__input", type="text", rows = "3", id="description") }}
                {{ form.description.label(class="mdl-textfield__label", for="description") }}
                {% if form.description.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.description.errors %}
                    <span style="color: red; font-size: 10;">{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}

            </div>
            <div> {{ form.submit(class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect
                mdl-button--accent")
                }}</div>



        </form>


    </div>
    <div class="mdl-cell--3-col">
        <h4>Playlist</h4>
        {% if songs %}
        <table class="mdl-data-table mdl-js-data-table">
            <thead>
                <tr>
                    <th class="mdl-data-table__cell--non-numeric"></th>
                    <th class="mdl-data-table__cell--non-numeric"></th>
                    <th class="mdl-data-table__cell--non-numeric"></th>
                    <th class="mdl-data-table__cell--non-numeric">Title</th>
                    <th class="mdl-data-table__cell--non-numeric">Artist</th>
                    <th class="mdl-data-table__cell--non-numeric">Duration</th>



                </tr>
            </thead>
            <tbody>
                {% for song in songs %}
                <tr>
                    <td class="mdl-data-table__cell--non-numeric">
                        <a href="{{ url_for('playlists.deleteSong', uuid=playlist.uuid, mbid=song.mbid) }}" ,
                            title="Delete">
                            <span class="material-icons" style="color:black;">
                                delete
                            </span>
                        </a>
                    </td>
                    <td class="mdl-data-table__cell--non-numeric">
                        <img src="{{ song.image }}" alt="" style="width: 50; height: 50; object-fit: cover;">
                    </td>
                    <td class="mdl-data-table__cell--non-numeric">
                        <audio controls>
                            <source src="{{ song.preview_url }}" type="audio/mpeg">
                            Your browser does not support the audio element.
                        </audio>
                    </td>
                    <td class="mdl-data-table__cell--non-numeric">{{ song.name }}</td>
                    <td class="mdl-data-table__cell--non-numeric">{{ song.artist }}</td>

                    <td class="mdl-data-table__cell--non-numeric">{{
                        (song.duration / 1000 // 60)|int }}:{{
                        (song.duration / 1000 % 60)|int }}

                    </td>
                    
                </tr>
                {% endfor %}
            </tbody>
        </table>

        {% else %}
        <h6>No songs in playlist</h6>
        {% endif %}

    </div>


</div>

<div class="mdl-grid">
    <div class="mdl-cell--4-col"></div>
    <div class="mdl-cell>">
        {% if top15 %}
        <h4>Recommendations</h4>
        <table class="mdl-data-table mdl-js-data-table">
            <thead>
                <tr>
                    <th class="mdl-data-table__cell--non-numeric"></th>
                    <th class="mdl-data-table__cell--non-numeric"></th>

                    <th class="mdl-data-table__cell--non-numeric">Title</th>
                    <th class="mdl-data-table__cell--non-numeric">Artist</th>
                    <th class="mdl-data-table__cell--non-numeric">Duration</th>



                </tr>
            </thead>
            <tbody>

                {% for ss in top15 %}
                <tr>

                    <td class="mdl-data-table__cell--non-numeric">
                        <img src="{{ ss.image }}" alt="" style="width: 50; height: 50; object-fit: cover;">
                    </td>
                    <td class="mdl-data-table__cell--non-numeric">
                        <audio controls>
                            <source src="{{ ss.preview_url }}" type="audio/mpeg">
                            Your browser does not support the audio element.
                        </audio>
                    </td>

                    <td class="mdl-data-table__cell--non-numeric">{{ ss.name }}</td>
                    <td class="mdl-data-table__cell--non-numeric">{{ ss.artist }}</td>
                    <td class="mdl-data-table__cell--non-numeric">{{
                        (ss.duration / 1000 // 60)|int }}:{{
                        (ss.duration / 1000 % 60)|int }}

                    </td>
                    <td class="mdl-data-table__cell--non-numeric">
                        <a href="{{ url_for('playlists.addSong', uuid=playlist.uuid, mbid=ss.mbid) }}" ,
                            title="Add To Playlist">
                            <span class="material-icons" style="color:black;">
                                add
                            </span>
                        </a>
                    </td>

                </tr>
                {% endfor %}
                {% else %}
                <h6>Add songs for some recommendations!</h6>

            </tbody>
        </table>
        {% endif %}
    </div>
    <div class="mdl-cell"></div>

</div>
{% endblock %}

flask_app/templates/header.html
{% extends "base.html" %}
{% block header %}

<!-- The drawer is always open in large screens. The header is always shown,
  even in small screens. -->
<div class="mdl-layout mdl-js-layout mdl-layout--fixed-drawer
  mdl-layout--fixed-header">
    <header class="mdl-layout__header">
        <div style="padding-top: 10px; padding-left: 10px;">
            {% with messages = get_flashed_messages() %}
            {% if messages %}
            {% for message in messages %}
    
                        <h6>{{ message }}</h6>
    
                        {% endfor %}
            {% endif %}
            {% endwith %}
        </div>

    </header>
    <div class="mdl-layout__drawer">
        <span class="mdl-layout-title">PlaylistsApp</span>
        {% if current_user.is_authenticated %}
        <span class="mdl-layout-title">Hello, {{ current_user.username }}!</span>
        {% endif %}


        <nav class="mdl-navigation">
            <a class="mdl-navigation__link" href="{{ url_for('playlists.index') }}">
                <i class="material-icons">home</i>
                Home</a>
            {% if current_user.is_authenticated %}
            <a class="mdl-navigation__link" href="{{ url_for('playlists.create') }}">
                <i class="material-icons">add</i>
                Create New Playlist</a>
            <a class="mdl-navigation__link" href="{{ url_for('user.account') }}">
                <i class="material-icons">person</i>
                Your Account</a>
            <a class="mdl-navigation__link" href="{{ url_for('user.logout') }}">
                <i class="material-icons">logout</i>
                Logout</a>
            {% else %}
            <a class="mdl-navigation__link" href="{{ url_for('user.login') }}">
                <i class="material-icons">login</i>
                Login/Register</a>

            {% endif %}


        </nav>
    </div>
    <main class="mdl-layout__content">


        {% block content %}

        <h1>OVERRIDE</h1>
        {% endblock %}

    </main>
</div>

{% endblock %}

flask_app/templates/login.html
{% extends "header.html" %}
{% block content %}

<script>

</script>
<h2>Log In</h2>
<div class="mdl-grid">
    <h6>If you don't have an account, then <a href="{{ url_for('user.register') }}">Register!</a></h4>
</div>

    


<div class="mdl-grid">

    <form action="" method="post">
        {{ form.csrf_token }}

        <div class="mdl-textfield mdl-js-textfield">

            {{ form.username(class="mdl-textfield__input", type="text", id="username", autocomplete="off") }}
            {{ form.username.label(class="mdl-textfield__label", for="username") }}
            
        </div>
        <div class="mdl-textfield mdl-js-textfield">

            {{ form.password(class="mdl-textfield__input", type="password", id="passsword", autocomplete="off") }}
            {{ form.password.label(class="mdl-textfield__label", for="password") }}
        
        </div>


        {{ form.submit(class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent") }}
    </form>
</div>
{% endblock %}

flask_app/templates/view.html
{% extends "header.html" %}
{% block content %}

<script>

</script>




<div class="mdl-grid">

    <div class="mdl-cell--3-col" style="padding-left: 40px;">

        <h4>Playlist Details:</h4>
        <form action="/" class="" method="POST">
            {{ form.csrf_token }}
            <div class="mdl-textfield mdl-js-textfield">
                {{ form.search_query(class="mdl-textfield__input", type="text", id="search_query", placeholder="Search For Playlists!", style="width:250;") }}

            </div>
            {% if form.search_query.errors %}
            <div class="alert alert-warning" role="alert">
                {% for error in form.search_query.errors %}
                <span style="color: red; font-size: 10;">{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
            {{ form.submit(class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent")
            }}




        </form>


    </div>


    <div class="mdl-cell--5-col">

        <h4>{{ playlist.name }} | Duration: {{ 
            (total_duration / 1000 // 60)|int }}:{{
            (total_duration / 1000 % 60)|int }}  </h4>
        <p>{{ playlist.description }}</p>
        <h6>Created by:  <a href="{{ url_for('user.view_account', username=playlist.owner.username)}}">{{ playlist.owner.username }}</a></h6>
        <h6>Number of songs: {{ songs|length }} | Likes {{ playlist.likes }}</h6>

        {% if liked %}

        <a href="{{ url_for('playlists.like', uuid=playlist.uuid) }}" , title="unlike">
            <span class="material-icons" style="color:red;">
                favorite
            </span>
        </a>
        {% else %}
        <a href="{{ url_for('playlists.like', uuid=playlist.uuid) }}" , title="like">
            <span class="material-icons" style="color:black;">
                favorite_border
            </span>
        </a>
        {% endif %}




        {% if songs %}
        <table class="mdl-data-table mdl-js-data-table" style="width: 800; padding-top: 50px;">
            <thead>
                <tr>
                    <th class="mdl-data-table__cell--non-numeric"></th>
                    <th class="mdl-data-table__cell--non-numeric"></th>

                    <th class="mdl-data-table__cell--non-numeric">Title</th>
                    <th class="mdl-data-table__cell--non-numeric">Artist</th>
                    <th class="mdl-data-table__cell--non-numeric">Duration</th>





                </tr>
            </thead>
            <tbody>
                {% for song in songs %}
                <tr>
                    <td class="mdl-data-table__cell--non-numeric">
                        <img src="{{ song.image }}" alt=""
                            style="width: 50; height: 50; object-fit: cover;">
                    </td>
                    <td class="mdl-data-table__cell--non-numeric">
                        <audio controls>
                            <source src="{{ song.preview_url }}" type="audio/mpeg">
                          Your browser does not support the audio element.
                          </audio>
                    </td>
                    <td class="mdl-data-table__cell--non-numeric">{{ song.name }}</td>
                    <td class="mdl-data-table__cell--non-numeric">{{ song.artist }}</td>
                    <td class="mdl-data-table__cell--non-numeric">{{ '{0:.2f}'.format(song.duration/ 1000 /60) }}
                    </td>

                </tr>
                {% endfor %}
            </tbody>
        </table>

        {% else %}
        <h6>No songs in playlist</h6>
        {% endif %}


    </div>


    <div class="mdl-cell--3-col">



    </div>


</div>

{% endblock %}